include ~/.cache/wal/colors-kitty.conf
# Set transparency (0.1 to 1.0)
background_opacity 0.8

# Allow changing opacity dynamically if needed
dynamic_background_opacity yes

# Try the most common names for the font
font_family      JetBrainsMono NFM
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Force the use of Nerd Font symbols if the main font fails
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols
