#!/bin/bash

# 1. Try to load colors from pywal (standard for Linux ricing)
# This file is automatically generated when you use 'wal' or similar tools
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
    source "$HOME/.cache/wal/colors.sh"
    # $color1 is usually the main accent color
    ACTIVE_COLOR=${color1}
else
    # Fallback: If no colors found, use Red so you know it ran
    ACTIVE_COLOR="#FF0000"
fi

# 2. Clean the color code (OpenRGB needs 'FF0000', not '#FF0000')
# This removes the '#' symbol
HEX_COLOR=${ACTIVE_COLOR:1}

# 3. Apply the color
# We use '|| true' so the script doesn't crash if OpenRGB isn't open yet
openrgb --mode direct --color "$HEX_COLOR" || true
