#################
### AUTOSTART ###
#################

# --- Enable the overview ---
exec-once = qs -c overview

# --- Enable the new Caelestia Shell ---
exec-once = caelestia shell

#############
### RULES ###
#############

layerrule = no_anim true, match:namespace caelestia-(launcher|osd|notifications|border-exclusion|area-p>
layerrule = animation fade, match:namespace caelestia-(drawers|background>
layerrule = order 1, match:namespace caelestia-border-exclusion
layerrule = order 2, match:namespace caelestia-bar
layerrule = xray 1, match:namespace caelestia-(border|launcher|bar|sidebar|navbar|mediadisplay|sc>
layerrule = blur true, match:namespace caelestia-.*
layerrule = blur true, match:namespace qs-.*
layerrule = ignore_alpha 0.10, match:namespace caelestia-.*


###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

# --- Caelestia Shortcuts ---

# Random Wallpaper (Super + Z)
bind = $mainMod, Z, exec, caelestia wallpaper --random

# Dark Mode (Super + X)
bind = $mainMod, X, exec, caelestia scheme set -m dark

# Light Mode (Super + Shift + X)
bind = $mainMod SHIFT, X, exec, caelestia scheme set -m light

# Lock Screen (Super + L)
bind = $mainMod, L, exec, caelestia shell lock lock

#search bar(super+R)
bind = $mainMod, R, exec, caelestia shell drawers toggle launcher

#TAB(SUPER+A)
bind = $mainMod, A, exec, qs ipc -c overview call overview toggle

#power menu(super+M)
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# Settings Menu (Opens GNOME Control Center, since you use Polkit-GNOME)
bind = $mainMod, I, exec, XDG_CURRENT_DESKTOP=GNOME gnome-control-center












